### PR TITLE
optimize temp data handling

### PR DESCRIPTION
**Pull request by ghost**
small optimizations by streamlining the handling of temperature data

**main changes:**
- ~~the dictionary for storing the tile temps seemed unnecessary, so it was removed, lmk if it was there for a specific reason~~
- resolved the TODO on line 70 regarding the sorting mechanism for remapping tile order, which should boost performance.

let me know if there are any issues or questions, love the plugin by the way.

### CODE REVIEW

**Comment by DoubleStrike** [comment]
I'll be reviewing this tonight and appreciate the PR and the kind words.

EDIT: I took a quick look. The reason the dictionary was used is that I need to order the tiles in a different order than they are listed if you just iterate thru the returned values in order. If you don't do that, you don't end up with a correctly-ordered list of tiles in knockout-js foreach template binding.

That's why I did an initial first pass populating the dictionary with the values from the serial line, and then a second pass against the reorderingMatrix to put them in the array in the correct order.

**Comment by DoubleStrike** [comment]
That does make me think I should name those variables better - perhaps ReportedOrderDictionary vs CustomizedOrderDictionary or something like that.

**Comment by ghost** [comment]
Made another commit which re-adds the dictionary, I added a few comments too so people can make more sense of the code. I _think_ the changes I made for the TODO on line 70 should still apply, but I'm too sleep-deprived to think.

**Comment by DoubleStrike** [comment]
Sounds good - I am just dealing with work emergencies but will get this merged this week.

**Review by DoubleStrike — APPROVED** [review]
Looks good.  Just need to test to make sure the tile order is correct with your iteration thru the reorderMatrix via foreach.

**Comment by DoubleStrike** [comment]
I realized after merge that you had accidentally moved some parentheses around which caused the script to not execute.  I moved those back and now it's good.  I released this as version 1.1.2.

**Pull request merged**
